name: Greeting data academy

on:
  push:
    branches-ignore: [main]

env:
  DAY_OF_WEEK: Monday
  WEEK_JOB: Something

jobs:
  greeting_job:
    runs-on: self-hosted
    env:
      GREETING: Hello
    steps:
      - name: "Say 'Hello Data Academy 7th edition, this is $DAY_OF_WEEK's first exercise! I'm <MY_NAME>'"
        run: echo "$GREETING $ACADEMY_TYPE Academy 7th edition, this is $DAY_OF_WEEK's first exercise! I'm $GITHUB_ACTOR"
        env:
          ACADEMY_TYPE: Data

  week_job:
    runs-on: self-hosted
    env: 
      WEEK_JOB: Something
    needs: greeting_job
    steps:
      - name: "Create connection between jobs"
        run: checkov -d ./S
        #echo "I'm a new job, and I'm connected to greeting_job"
        




